-- 🔹 Query 1: Monthly Revenue Trend
-- Purpose: Track revenue trends over each month to identify seasonality and performance.
SELECT
    DATE_FORMAT(Order_Date, '%Y-%m') AS Month,       -- Extract month and year (e.g., '2023-01')
    SUM(Revenue) AS Total_Revenue                    -- Total revenue per month
FROM
    sales_data
GROUP BY
    Month                                            -- Group data by formatted month
ORDER BY
    Month;                                           -- Sort results chronologically


-- 🔹 Query 2: Revenue by Category
-- Purpose: Identify which product categories contribute the most to revenue.
SELECT
    Category,                                        -- Product category (e.g., Electronics, Furniture)
    SUM(Revenue) AS Category_Revenue                 -- Total revenue per category
FROM
    sales_data
GROUP BY
    Category
ORDER BY
    Category_Revenue DESC;                           -- Sort by highest to lowest revenue


-- 🔹 Query 3: Top 10 Products by Revenue
-- Purpose: Highlight the top-performing products based on total revenue.
SELECT
    Product_ID,                                      -- Product identifier
    SUM(Revenue) AS Product_Revenue                  -- Total revenue generated by each product
FROM
    sales_data
GROUP BY
    Product_ID
ORDER BY
    Product_Revenue DESC                             -- Highest earning products first
LIMIT 10;                                            -- Only show top 10 products


-- 🔹 Query 4: Region-wise Sales
-- Purpose: Understand regional distribution of revenue to optimize regional strategies.
SELECT
    Region,                                          -- Sales region (e.g., North, South)
    SUM(Revenue) AS Region_Revenue                   -- Total revenue from each region
FROM
    sales_data
GROUP BY
    Region
ORDER BY
    Region_Revenue DESC;                             -- Highest revenue-generating regions on top
